### ISSUE TITLE
Need to setup initial express app structure

### ISSUE THREAD

**Issue by williamrice** [Server-404-error/notes-server#2]
This is opinionated, feedback welcome. But if not, I'll follow this with a modification of server.js instead of index.js

![image](https://user-images.githubusercontent.com/25677840/208312007-1900dced-efe0-4a9b-9126-60349bbc491e.png)

**Comment by williamrice** [comment]
Also we will have a .env in the root, but we will only commit a .env.example with all the env vars so new devs can know what to set

**Comment by moussaTayeb** [comment]
i think this is the best architecture for this project

**Comment by williamrice** [comment]
Its a good start, we will obviously adjust as we go on! I just don't want all the routes inside one file and I'll be happy!

**Comment by moussaTayeb** [comment]
i've made this structure, and put the started code
