### ISSUE TITLE
Initial database schema required

### ISSUE THREAD

**Issue by williamrice** [Server-404-error/notes-server#3]
@moussaTayeb  has said he will create a diagram that will be posted here so we can update the prisma scheme with the db design. 

Once the schema diagram is posted, someone can model the db schema in the prisma file.

**Comment by moussaTayeb** [comment]
I've completed the scheme @williamrice if there is any problem, tell me and i'll fix it, i will give more explanations about the diagram in discord
![Untitled Diagram drawio](https://user-images.githubusercontent.com/56636785/208516904-14d90327-211f-4dd4-9f89-2769f292e891.png)
